import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import CustomSessionProvider from "@/components/SessionProvider";
import { CartProvider } from "@/context/CartContext"; // 🔥 Import du CartProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomSessionProvider>
          <AuthProvider>
            <CartProvider>
              {" "}
              {/* 🔥 On englobe toute l'app avec le panier */}
              {children}
            </CartProvider>
          </AuthProvider>
        </CustomSessionProvider>
      </body>
    </html>
  );
}
